### PR TITLE
Should be pretty complete now...

### PR DESCRIPTION
**Pull request by cpt-lamar**

### CODE REVIEW

**Comment by osixia** [comment]
Merci beaucoup :)

**Comment by cpt-lamar** [comment]
Hi, I did some testing after submitting the pull request (yes, the normal way ;-)  ) and it seems that some 'quotes' in the translated text are breaking mosaico editor

**Comment by osixia** [comment]
:O :D 
I didn't noticed that to you have any example ?

**Comment by cpt-lamar** [comment]
In my setup (using Firefox - I did not try with other browsers), when I launch mosaico after switching to french translation, it just hangs... nothing happens.
With Development tools on, I saw that a javascript error was triggered because of the quote in "MOSAICO Création d'Emails Adaptatifs". I did not have the time to investigate more yet.

**Pull request merged**
